package com.ohdoking.dansoondiary.common;

import android.graphics.Color;

import com.ohdoking.dansoondiary.R;

/**
 * Created by Administrator on 2016-03-15.
 */
public class DsStatic {


    /*public static Integer[] buttonList = {
            R.drawable.add_etc,
            R.drawable.diary_null_icon,
            R.drawable.diary_icon_1,
            R.drawable.diary_icon_2,
            R.drawable.diary_icon_3,
            R.drawable.diary_icon_4,
            R.drawable.diary_icon_5,
            R.drawable.diary_icon_6,
            R.drawable.diary_icon_7,
            R.drawable.diary_icon_8,
            R.drawable.diary_icon_9,
            R.drawable.diary_icon_10,
            R.drawable.diary_icon_11,
            R.drawable.diary_icon_12,
            R.drawable.diary_icon_13,
            R.drawable.diary_icon_14,
            R.drawable.diary_icon_15,
            R.drawable.diary_icon_16,
            R.drawable.diary_icon_17,
            R.drawable.diary_icon_18,
            R.drawable.diary_icon_19,
            R.drawable.diary_icon_20,
            R.drawable.diary_icon_21,
            R.drawable.diary_icon_22,
            R.drawable.diary_icon_23,
            R.drawable.diary_icon_24,
            R.drawable.diary_icon_25,
            R.drawable.diary_icon_26,
            R.drawable.diary_icon_27,
            R.drawable.diary_icon_28,
            R.drawable.diary_icon_29,
            R.drawable.diary_icon_30,
            R.drawable.diary_icon_31,
            R.drawable.diary_icon_32,
            R.drawable.diary_icon_33,
            R.drawable.diary_icon_34,
            R.drawable.diary_icon_35,
            R.drawable.diary_icon_36,
            R.drawable.diary_icon_37,
            R.drawable.diary_icon_38,
            R.drawable.diary_icon_39,
            R.drawable.diary_icon_40};
    public static Integer[] buttonListRev = {
            R.drawable.add_etc,
            R.drawable.diary_null_icon,
            R.drawable.diary_icon_rev_1,
            R.drawable.diary_icon_rev_2,
            R.drawable.diary_icon_rev_3,
            R.drawable.diary_icon_rev_4,
            R.drawable.diary_icon_rev_5,
            R.drawable.diary_icon_rev_6,
            R.drawable.diary_icon_rev_7,
            R.drawable.diary_icon_rev_8,
            R.drawable.diary_icon_rev_9,
            R.drawable.diary_icon_rev_10,
            R.drawable.diary_icon_rev_11,
            R.drawable.diary_icon_rev_12,
            R.drawable.diary_icon_rev_13,
            R.drawable.diary_icon_rev_14,
            R.drawable.diary_icon_rev_15,
            R.drawable.diary_icon_rev_16,
            R.drawable.diary_icon_rev_17,
            R.drawable.diary_icon_rev_18,
            R.drawable.diary_icon_rev_19,
            R.drawable.diary_icon_rev_20,
            R.drawable.diary_icon_rev_21,
            R.drawable.diary_icon_rev_22,
            R.drawable.diary_icon_rev_23,
            R.drawable.diary_icon_rev_24,
            R.drawable.diary_icon_rev_25,
            R.drawable.diary_icon_rev_26,
            R.drawable.diary_icon_rev_27,
            R.drawable.diary_icon_rev_28,
            R.drawable.diary_icon_rev_29,
            R.drawable.diary_icon_rev_30,
            R.drawable.diary_icon_rev_31,
            R.drawable.diary_icon_rev_32,
            R.drawable.diary_icon_rev_33,
            R.drawable.diary_icon_rev_34,
            R.drawable.diary_icon_rev_35,
            R.drawable.diary_icon_rev_36,
            R.drawable.diary_icon_rev_37,
            R.drawable.diary_icon_rev_38,
            R.drawable.diary_icon_rev_39,
            R.drawable.diary_icon_rev_40
    };*/

    public static Integer[] buttonList46p5 = {
            R.drawable.add_etc,
            R.drawable.diary_null_icon,
            R.drawable.diary_icon_46_2,
            R.drawable.diary_icon_46_3,
            R.drawable.diary_icon_46_4,
            R.drawable.diary_icon_46_5,
            R.drawable.diary_icon_46_6,
            R.drawable.diary_icon_46_7,
            R.drawable.diary_icon_46_8,
            R.drawable.diary_icon_46_9,
            R.drawable.diary_icon_46_10,
            R.drawable.diary_icon_46_11,
            R.drawable.diary_icon_46_12,
            R.drawable.diary_icon_46_13,
            R.drawable.diary_icon_46_14,
            R.drawable.diary_icon_46_15,
            R.drawable.diary_icon_46_16,
            R.drawable.diary_icon_46_17,
            R.drawable.diary_icon_46_18,
            R.drawable.diary_icon_46_19,
            R.drawable.diary_icon_46_20,
            R.drawable.diary_icon_46_21,
            R.drawable.diary_icon_46_22,
            R.drawable.diary_icon_46_23,
            R.drawable.diary_icon_46_24,
            R.drawable.diary_icon_46_25,
            R.drawable.diary_icon_46_26,
            R.drawable.diary_icon_46_27,
            R.drawable.diary_icon_46_28,
            R.drawable.diary_icon_46_29,
            R.drawable.diary_icon_46_30,
            R.drawable.diary_icon_46_31,
            R.drawable.diary_icon_46_32,
            R.drawable.diary_icon_46_33,
            R.drawable.diary_icon_46_34,
            R.drawable.diary_icon_46_35,
            R.drawable.diary_icon_46_36,
            R.drawable.diary_icon_46_37,
            R.drawable.diary_icon_46_38,
            R.drawable.diary_icon_46_39,
            R.drawable.diary_icon_46_40,
            R.drawable.diary_icon_46_41,
            R.drawable.diary_icon_46_42,
            R.drawable.diary_icon_46_43,
            R.drawable.diary_icon_46_44,
            R.drawable.diary_icon_46_45,
            R.drawable.diary_icon_46_46,
            R.drawable.diary_icon_46_47,
            R.drawable.diary_icon_46_48,
            R.drawable.diary_icon_46_49
    };

    public static Integer[] buttonList44 = {
            R.drawable.add_etc,
            R.drawable.diary_null_icon,
            R.drawable.diary_icon_q_44_2,
            R.drawable.diary_icon_q_44_3,
            R.drawable.diary_icon_q_44_4,
            R.drawable.diary_icon_q_44_5,
            R.drawable.diary_icon_q_44_6,
            R.drawable.diary_icon_q_44_7,
            R.drawable.diary_icon_q_44_8,
            R.drawable.diary_icon_q_44_9,
            R.drawable.diary_icon_q_44_10,
            R.drawable.diary_icon_q_44_11,
            R.drawable.diary_icon_q_44_12,
            R.drawable.diary_icon_q_44_13,
            R.drawable.diary_icon_q_44_14,
            R.drawable.diary_icon_q_44_15,
            R.drawable.diary_icon_q_44_16,
            R.drawable.diary_icon_q_44_17,
            R.drawable.diary_icon_q_44_18,
            R.drawable.diary_icon_q_44_19,
            R.drawable.diary_icon_q_44_20,
            R.drawable.diary_icon_q_44_21,
            R.drawable.diary_icon_q_44_22,
            R.drawable.diary_icon_q_44_23,
            R.drawable.diary_icon_q_44_24,
            R.drawable.diary_icon_q_44_25,
            R.drawable.diary_icon_q_44_26,
            R.drawable.diary_icon_q_44_27,
            R.drawable.diary_icon_q_44_28,
            R.drawable.diary_icon_q_44_29,
            R.drawable.diary_icon_q_44_30,
            R.drawable.diary_icon_q_44_31,
            R.drawable.diary_icon_q_44_32,
            R.drawable.diary_icon_q_44_33,
            R.drawable.diary_icon_q_44_34,
            R.drawable.diary_icon_q_44_35,
            R.drawable.diary_icon_q_44_36,
            R.drawable.diary_icon_q_44_37,
            R.drawable.diary_icon_q_44_38,
            R.drawable.diary_icon_q_44_39,
            R.drawable.diary_icon_q_44_40,
            R.drawable.diary_icon_q_44_41,
            R.drawable.diary_icon_q_44_42,
            R.drawable.diary_icon_q_44_43,
            R.drawable.diary_icon_q_44_44,
            R.drawable.diary_icon_q_44_45,
            R.drawable.diary_icon_q_44_46,
            R.drawable.diary_icon_q_44_47,
            R.drawable.diary_icon_q_44_48,
            R.drawable.diary_icon_q_44_49
    };
    public static Integer[] buttonList44Rev = {
            R.drawable.add_etc,
            R.drawable.diary_null_icon,
            R.drawable.diary_icon_44_2,
            R.drawable.diary_icon_44_3,
            R.drawable.diary_icon_44_4,
            R.drawable.diary_icon_44_5,
            R.drawable.diary_icon_44_6,
            R.drawable.diary_icon_44_7,
            R.drawable.diary_icon_44_8,
            R.drawable.diary_icon_44_9,
            R.drawable.diary_icon_44_10,
            R.drawable.diary_icon_44_11,
            R.drawable.diary_icon_44_12,
            R.drawable.diary_icon_44_13,
            R.drawable.diary_icon_44_14,
            R.drawable.diary_icon_44_15,
            R.drawable.diary_icon_44_16,
            R.drawable.diary_icon_44_17,
            R.drawable.diary_icon_44_18,
            R.drawable.diary_icon_44_19,
            R.drawable.diary_icon_44_20,
            R.drawable.diary_icon_44_21,
            R.drawable.diary_icon_44_22,
            R.drawable.diary_icon_44_23,
            R.drawable.diary_icon_44_24,
            R.drawable.diary_icon_44_25,
            R.drawable.diary_icon_44_26,
            R.drawable.diary_icon_44_27,
            R.drawable.diary_icon_44_28,
            R.drawable.diary_icon_44_29,
            R.drawable.diary_icon_44_30,
            R.drawable.diary_icon_44_31,
            R.drawable.diary_icon_44_32,
            R.drawable.diary_icon_44_33,
            R.drawable.diary_icon_44_34,
            R.drawable.diary_icon_44_35,
            R.drawable.diary_icon_44_36,
            R.drawable.diary_icon_44_37,
            R.drawable.diary_icon_44_38,
            R.drawable.diary_icon_44_39,
            R.drawable.diary_icon_44_40,
            R.drawable.diary_icon_44_41,
            R.drawable.diary_icon_44_42,
            R.drawable.diary_icon_44_43,
            R.drawable.diary_icon_44_44,
            R.drawable.diary_icon_44_45,
            R.drawable.diary_icon_44_46,
            R.drawable.diary_icon_44_47,
            R.drawable.diary_icon_44_48,
            R.drawable.diary_icon_44_49
    };

    public static Integer[] buttonList69 = {
            R.drawable.add_etc,
            R.drawable.diary_null_icon,
            R.drawable.diary_icon_49_2,
            R.drawable.diary_icon_49_3,
            R.drawable.diary_icon_49_4,
            R.drawable.diary_icon_49_5,
            R.drawable.diary_icon_49_6,
            R.drawable.diary_icon_49_7,
            R.drawable.diary_icon_49_8,
            R.drawable.diary_icon_49_9,
            R.drawable.diary_icon_49_10,
            R.drawable.diary_icon_49_11,
            R.drawable.diary_icon_49_12,
            R.drawable.diary_icon_49_13,
            R.drawable.diary_icon_49_14,
            R.drawable.diary_icon_49_15,
            R.drawable.diary_icon_49_16,
            R.drawable.diary_icon_49_17,
            R.drawable.diary_icon_49_18,
            R.drawable.diary_icon_49_19,
            R.drawable.diary_icon_49_20,
            R.drawable.diary_icon_49_21,
            R.drawable.diary_icon_49_22,
            R.drawable.diary_icon_49_23,
            R.drawable.diary_icon_49_24,
            R.drawable.diary_icon_49_25,
            R.drawable.diary_icon_49_26,
            R.drawable.diary_icon_49_27,
            R.drawable.diary_icon_49_28,
            R.drawable.diary_icon_49_29,
            R.drawable.diary_icon_49_30,
            R.drawable.diary_icon_49_31,
            R.drawable.diary_icon_49_32,
            R.drawable.diary_icon_49_33,
            R.drawable.diary_icon_49_34,
            R.drawable.diary_icon_49_35,
            R.drawable.diary_icon_49_36,
            R.drawable.diary_icon_49_37,
            R.drawable.diary_icon_49_38,
            R.drawable.diary_icon_49_39,
            R.drawable.diary_icon_49_40,
            R.drawable.diary_icon_49_41,
            R.drawable.diary_icon_49_42,
            R.drawable.diary_icon_49_43,
            R.drawable.diary_icon_49_44,
            R.drawable.diary_icon_49_45,
            R.drawable.diary_icon_49_46,
            R.drawable.diary_icon_49_47,
            R.drawable.diary_icon_49_48,
            R.drawable.diary_icon_49_49
    };

    public static Integer[] buttonList29 = {
            R.drawable.add_etc,
            R.drawable.diary_null_icon,
            R.drawable.diary_icon_29_2,
            R.drawable.diary_icon_29_3,
            R.drawable.diary_icon_29_4,
            R.drawable.diary_icon_29_5,
            R.drawable.diary_icon_29_6,
            R.drawable.diary_icon_29_7,
            R.drawable.diary_icon_29_8,
            R.drawable.diary_icon_29_9,
            R.drawable.diary_icon_29_10,
            R.drawable.diary_icon_29_11,
            R.drawable.diary_icon_29_12,
            R.drawable.diary_icon_29_13,
            R.drawable.diary_icon_29_14,
            R.drawable.diary_icon_29_15,
            R.drawable.diary_icon_29_16,
            R.drawable.diary_icon_29_17,
            R.drawable.diary_icon_29_18,
            R.drawable.diary_icon_29_19,
            R.drawable.diary_icon_29_20,
            R.drawable.diary_icon_29_21,
            R.drawable.diary_icon_29_22,
            R.drawable.diary_icon_29_23,
            R.drawable.diary_icon_29_24,
            R.drawable.diary_icon_29_25,
            R.drawable.diary_icon_29_26,
            R.drawable.diary_icon_29_27,
            R.drawable.diary_icon_29_28,
            R.drawable.diary_icon_29_29,
            R.drawable.diary_icon_29_30,
            R.drawable.diary_icon_29_31,
            R.drawable.diary_icon_29_32,
            R.drawable.diary_icon_29_33,
            R.drawable.diary_icon_29_34,
            R.drawable.diary_icon_29_35,
            R.drawable.diary_icon_29_36,
            R.drawable.diary_icon_29_37,
            R.drawable.diary_icon_29_38,
            R.drawable.diary_icon_29_39,
            R.drawable.diary_icon_29_40,
            R.drawable.diary_icon_29_41,
            R.drawable.diary_icon_29_42,
            R.drawable.diary_icon_29_43,
            R.drawable.diary_icon_29_44,
            R.drawable.diary_icon_29_45,
            R.drawable.diary_icon_29_46,
            R.drawable.diary_icon_29_47,
            R.drawable.diary_icon_29_48,
            R.drawable.diary_icon_29_49
    };

    public static Integer[] buttonColor = {
            Color.rgb(240,91,82),
            Color.rgb(240,91,82),
            Color.rgb(177, 210, 56),
            Color.rgb(131, 211, 237),
            Color.rgb(177, 210, 56),
            Color.rgb(254, 204, 61),
            Color.rgb(152, 81, 159),
            Color.rgb(177, 210, 56),
            Color.rgb(240,91,82),
            Color.rgb(240,91,82),
            Color.rgb(118, 135, 195),
            Color.rgb(238, 78, 152),
            Color.rgb(118, 135, 195),
            Color.rgb(177, 210, 56),
            Color.rgb(118, 135, 195),
            Color.rgb(254, 204, 61),
            Color.rgb(152, 81, 159),
            Color.rgb(254, 204, 61),
            Color.rgb(240,91,82),
            Color.rgb(118, 135, 195),
            Color.rgb(238, 78, 152),
            Color.rgb(238, 78, 152),
            Color.rgb(238, 78, 152),
            Color.rgb(152, 81, 159),
            Color.rgb(240,91,82),
            Color.rgb(254, 204, 61),
            Color.rgb(240,91,82),
            Color.rgb(131, 211, 237),
            Color.rgb(249, 175, 65),
            Color.rgb(249, 175, 65),
            Color.rgb(177, 210, 56),
            Color.rgb(240,91,82),
            Color.rgb(254, 204, 61),
            Color.rgb(152, 81, 159),
            Color.rgb(238, 78, 152),
            Color.rgb(131, 211, 237),
            Color.rgb(131, 211, 237),
            Color.rgb(254, 204, 61),
            Color.rgb(131, 211, 237),
            Color.rgb(238, 78, 152),
            Color.rgb(152, 81, 159),
            Color.rgb(131, 211, 237),
            Color.rgb(254, 204, 61),
            Color.rgb(177, 210, 56),
            Color.rgb(249, 175, 65),
            Color.rgb(152, 81, 159),
            Color.rgb(254, 204, 61),
            Color.rgb(177, 210, 56),
            Color.rgb(118, 135, 195),
            Color.rgb(249, 175, 65),
    };


    public static final String USERINFO = "userinfo";
    public static final String VISITSTATE = "visit-state";

    public static final String SHARDPREFERENCETABLE = "password";
    public static final String USEPASSWORD = "usepassword";
    public static final String PASSWORDSATE = "password-activity-state";

    public static final String ICONLIST = "iconlist";
    public static final String ICONFIRSTTIME = "iconlist-first-time";
    public static final String ICONNORMALTIME = "iconlist-normal-time";

    public static final String ICONTABLE = "icon";
    public static final String FAVORITEICON = "favorite-icon";

    public static final int SETPASSWORD = 1;
    public static final int CONFIRMPASSWORD = 2;

    public static final String STARTACTIVITY = "where";
    public static final String NORMALDIARYACTIVITY = "normal";
    public static final String MODIDIARYACTIVITY = "modi";

    public static final int NOCHANGE = 0;
    public static final int CHANGE = 1;
}
